[project]
name = "neuro-curvature"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "mne>=1.11.0",
    "numpy>=2.4.1",
    "scipy>=1.17.0",
    "snntorch>=0.9.4",
    "torch>=2.10.0",
]
